apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  labels:
    app: api
data:
  POSTGRES_SERVICE: db
  POSTGRES_PORT: "5432"
  POSTGRES_DB_NAME: postgresdb
  POSTGRES_USER: postgres_user
  POSTGRES_PASSWORD: postgres_password