apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: gcr.io/studious-loader-278016/users-service-api:0.0.6
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-config
